Write a Numpy program to get the Numpy version and show the Numpy build configuration

In [1]:
import numpy as np

In [2]:
print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


In [3]:
print("NumPy Build Configuration:")
np.show_config()


NumPy Build Configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    l

Write a NumPy program to get help with the add function.

In [4]:
help(np.add) #this is the documentation about add function (How does it work? What does it take? What is the return?)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

Write a NumPy program to test whether none of the elements of a given array are zero.

In [7]:
x = np.array([1, 4, 3, 5])
print("There is No zero in the array ?")
print(np.all(x)) # It shows if there is No zero in the array or not by retern true or false.

There is No zero in the array ?
True


In [8]:
x = np.array([1, 4, 0, 5])
print("There is No zero in the array ?")
print(np.all(x)) # It shows if there is No zero in the array or not by retern true or false.

There is No zero in the array ?
False


Write a NumPy program to test if any of the elements of a given array are non-zero.

In [10]:
x = np.array([0, 4, 0, 0])
print("Are all the numbers in the array not zero ?")
print(np.any(x)) # It shows if all the elemnt on array are non-zero or not by retern true or false.

Are all the numbers in the array not zero ?
True


In [11]:
x = np.array([0, 0, 0, 0])
print("Are all the numbers in the array not zero ?")
print(np.any(x)) # It shows if all the elemnt on array are non-zero or not by retern true or false.

Are all the numbers in the array not zero ?
False


Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [23]:
x = np.array([1, 4, 3,np.nan, np.inf, -np.inf ])
print("retern true if it finite number esle return false")
print(np.isfinite(x))


retern true if it finite number esle return false
[ True  True  True False False False]


Write a NumPy program to test elements-wise for positive or negative infinity.

In [24]:
x = np.array([1, 4, -3,np.nan, np.inf, -np.inf ])
print("retern true if it infinite positive number esle return false")
print(np.isposinf(x))

retern true if it infinite positive number esle return false
[False False False False  True False]


In [25]:
x = np.array([1, 4, -3,np.nan, np.inf, -np.inf ])
print("retern true if it infinite negative number esle return false")
print(np.isneginf(x))

retern true if it infinite negative number esle return false
[False False False False False  True]


Write a NumPy program to test element-wise for NaN of a given array.

In [26]:
x = np.array([1, 4, -3,np.nan, np.inf, -np.inf ])
print("if it not a number retern true else return false")
print(np.isnan(x))

if it not a number retern true else return false
[False False False  True False False]


Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.

In [33]:
x = np.array([1, 4, -3, 2+1j])
print("retern true if it complex number esle return false")
print(np.iscomplex(x))
print("retern true if it real number esle return false")
print(np.isreal(x))
print("Checking if it's type is scaler ")
print(np.isscalar(1.2)) # Check if the value is a single number (not a list or array)
print("Checking if it's type is scaler ")
print(np.isscalar([1.2])) # Check if the value is a single number (not a list or array)

retern true if it complex number esle return false
[False False False  True]
retern true if it real number esle return false
[ True  True  True False]
Checking if it's type is scaler 
True
Checking if it's type is scaler 
False


Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [34]:
a = np.array([1.0, 2.00001, 3.0])
b = np.array([1.0, 2.00002, 3.00001])

# Check if the elements are equal within a tolerance
result = np.allclose(a, b, rtol=1e-05, atol=1e-08)

print("Arrays are element-wise equal within tolerance:", result) # Check if all elements in both arrays are almost equal (allows small differences)


Arrays are element-wise equal within tolerance: True


Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [37]:
x = np.array([1, 3])
y = np.array([2, 3])
# Check if elements in x are greater than corresponding elements in y
print("Comparison - greater")
print(np.greater(x, y))  # [False False] → 1 > 2 (False), 3 > 3 (False)

# Check if elements in x are greater than or equal to elements in y
print("Comparison - greater_equal")
print(np.greater_equal(x, y))  # [False True] → 1 >= 2 (False), 3 >= 3 (True)

# Check if elements in x are less than corresponding elements in y
print("Comparison - less")
print(np.less(x, y))  # [True False] → 1 < 2 (True), 3 < 3 (False)

Comparison - greater
[False False]
Comparison - greater_equal
[False  True]
Comparison - less
[ True False]


Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [38]:
a = np.array([1, 2.00001, 3])
b = np.array([1, 2.00002, 3.00001])

# Element-wise exact comparison
print("Element-wise exact comparison:")
print(np.equal(a, b))  # Will return False where there's any small difference

print("\nElement-wise comparison within tolerance:")
print(np.isclose(a, b, rtol=1e-05, atol=1e-08))  # Returns True if close enough


Element-wise exact comparison:
[ True False False]

Element-wise comparison within tolerance:
[ True  True  True]


Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [39]:
X = np.array([1, 7, 13, 105])
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize)) # Memory size = number of elements (X.size) × size of each element in bytes (X.itemsize)

Size of the memory occupied by the said array:
32 bytes


Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

In [42]:
# Create an array of 10 zeros
array = np.zeros(10)
print("An array of 10 zeros:")
print(array)

# Create an array of 10 ones
array = np.ones(10)
print("An array of 10 ones:")
print(array)

# Create an array of 10 fives by multiplying ones by 5
array = np.ones(10) * 5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of integers from 30 to 70.

In [44]:
# Create an array of integers starting from 30 up to (and including) 70
# Note: np.arange(30, 71) generates numbers from 30 to 70 because the stop value (71) is excluded
array = np.arange(30, 71)
print("Array of the integers from 30 to 70")

# Printing the array of integers from 30 to 70
print(array)

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Write a NumPy program to create an array of all even integers from 30 to 70.

In [46]:
# Create an array of integers from 30 to 70 with a step of 2(only even numbers)
# np.arange(start, stop, step) → generates numbers from start to (stop - 1), increasing by step
array = np.arange( 30 , 71 , 2 )
print("Array of the integers from 30 to 70")

# Printing the array of integers from 30 to 70
print(array)

Array of the integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Write a NumPy program to create a 3x3 identity matrix.

In [47]:
# Creating a 3x3 identity matrix
array_2D = np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a NumPy program to generate a random number between 0 and 1.

In [48]:
random_number = np.random.rand()# Generate a random float number between 0 and 1
print("Random number between 0 and 1:")
print(random_number)

Random number between 0 and 1:
0.5812421859818095


Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [49]:
# Generate an array of 15 random numbers from a standard normal distribution
random_array = np.random.randn(15)
print("Array of 15 random numbers from a standard normal distribution:")
print(random_array)


Array of 15 random numbers from a standard normal distribution:
[-2.20588463 -1.49262753  1.45567271  1.02658288 -0.30958696  0.87109281
 -0.77394676  0.12621164 -0.4172879  -0.26003318  1.22189001 -0.1533731
 -0.10169152  1.22345331  0.76143348]


Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last

In [50]:
x = np.arange(15, 55)
# Printing a message indicating all values  except the first and last elements using slicing [1:-1]
print("All values except the first and last of the said vector:")
print(x[1:-1])

All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


Write a NumPy program to create a 3X4 array and iterate over it.

In [51]:
a = np.arange(10, 22).reshape((3, 4))
print("Original array:")
print(a)

# Printing a message indicating each element of the array using np.nditer() to iterate through the elements
print("Each element of the array is:")
for x in np.nditer(a):
    print(x, end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

Write a NumPy program to create a vector of length 10 with values ​​evenly distributed between 5 and 50.

In [52]:
# Creating an array 'v' with length 5, evenly distributed values between 10 and 49 using np.linspace()
v = np.linspace(10, 49, 5)

print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [53]:
# Create a vector with values from 0 to 20
vector = np.arange(21)

print("Original vector:")
print(vector)

# Change the sign of elements between 9 and 15 (inclusive)
vector[(vector >= 9) & (vector <= 15)] *= -1

print("\nVector after changing the sign of numbers from 9 to 15:")
print(vector)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Vector after changing the sign of numbers from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [54]:
# Create a vector of length 5 with random integers from 0 to 10
vector = np.random.randint(0, 11, size=5)

print("Vector of 5 random integers from 0 to 10:")
print(vector)

Vector of 5 random integers from 0 to 10:
[3 1 9 6 5]


Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.


In [55]:
array = np.arange(10, 22)

# Reshape it into a 3x4 matrix
matrix = array.reshape(3, 4)

print("3x4 matrix with values from 10 to 21:")
print(matrix)

3x4 matrix with values from 10 to 21:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


Write a NumPy program to find the number of rows and columns in a given matrix.

In [56]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

# Get the shape of the matrix
rows, columns = matrix.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 4
Number of columns: 3


Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [58]:
matrix = np.zeros((10, 10), dtype=int)

# Set the border elements to 1
matrix[0, :] = 1         # Top row
matrix[-1, :] = 1        # Bottom row
matrix[:, 0] = 1         # Left column
matrix[:, -1] = 1        # Right column

print("10x10 matrix with 1s on the border and 0s inside:")
print(matrix)

10x10 matrix with 1s on the border and 0s inside:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


Sure! Here's a NumPy program that creates a 5×5 zero matrix and sets the main diagonal elements to 1, 2, 3, 4, 5:

In [59]:
matrix = np.zeros((5, 5), dtype=int)

# Set the main diagonal
np.fill_diagonal(matrix, [1, 2, 3, 4, 5])

print("5x5 matrix with diagonal [1, 2, 3, 4, 5]:")
print(matrix)

5x5 matrix with diagonal [1, 2, 3, 4, 5]:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [60]:
matrix = np.fromfunction(lambda i, j: (i + j) % 2, (4, 4), dtype=int)

# Set the main diagonal to 0
np.fill_diagonal(matrix, 0)

print("4x4 staggered matrix with 0s on the main diagonal:")
print(matrix)

4x4 staggered matrix with 0s on the main diagonal:
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [61]:
array = np.random.rand(3, 3, 3)

print("3x3x3 array with arbitrary values:")
print(array)


3x3x3 array with arbitrary values:
[[[0.01892173 0.62257762 0.27342594]
  [0.29961214 0.24020565 0.47034099]
  [0.43615222 0.28028567 0.00439689]]

 [[0.06196146 0.54943822 0.754005  ]
  [0.1804785  0.05791075 0.76281596]
  [0.98200325 0.21070941 0.6974644 ]]

 [[0.7763909  0.6878023  0.90149225]
  [0.661863   0.38939415 0.68922065]
  [0.85726698 0.06340094 0.72964567]]]


Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.

In [62]:
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Sum of all elements
total_sum = np.sum(array)

# Sum of each column (axis=0)
column_sum = np.sum(array, axis=0)

# Sum of each row (axis=1)
row_sum = np.sum(array, axis=1)


print("Original Array:")
print(array)

print("\nSum of all elements:", total_sum)
print("Sum of each column:", column_sum)
print("Sum of each row:", row_sum)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]


Write a NumPy program to compute the inner product of two given vectors

In [63]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Compute the inner (dot) product
inner_product = np.dot(vector1, vector2)


print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Inner product of the two vectors:", inner_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Inner product of the two vectors: 32


Write a NumPy program to add a vector to each row of a given matrix.

In [64]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Define a vector to add to each row
vector = np.array([10, 20, 30])

# Add the vector to each row of the matrix
result = matrix + vector


print("Original matrix:")
print(matrix)

print("\nVector to add:")
print(vector)

print("\nResult after adding the vector to each row:")
print(result)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector to add:
[10 20 30]

Result after adding the vector to each row:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


Write a NumPy program to save a given array to a binary file .

In [67]:
array = np.array([1, 2, 3, 4, 5])

# Save the array to a binary file with .npy extension
np.save('my_array.npy', array)

print("Array saved to 'my_array.npy' successfully.")

Array saved to 'my_array.npy' successfully.


Write a NumPy program to save a given array to a binary file.

In [69]:
array = np.array([10, 20, 30, 40, 50])

# Save the array to a binary .npy file
np.save('saved_array.npy', array)

print("Array saved to 'saved_array.npy' successfully.")


Array saved to 'saved_array.npy' successfully.


Write a NumPy program to save a given array to a text file and load it.

In [70]:
array = np.array([1.5, 2.5, 3.5, 4.5, 5.5])

# Save the array to a text file
np.savetxt('array.txt', array)

print("Array saved to 'array.txt' successfully.")

# Load the array back from the text file
loaded_array = np.loadtxt('array.txt')

print("Array loaded from 'array.txt':")
print(loaded_array)

Array saved to 'array.txt' successfully.
Array loaded from 'array.txt':
[1.5 2.5 3.5 4.5 5.5]


Write a NumPy program to convert a given array into bytes, and load it as an array.



In [71]:
original_array = np.array([10, 20, 30, 40, 50], dtype=np.int32)

# Convert the array to bytes
array_bytes = original_array.tobytes()

print("Array converted to bytes:")
print(array_bytes)

# Load the array back from bytes
restored_array = np.frombuffer(array_bytes, dtype=np.int32)

print("\nArray restored from bytes:")
print(restored_array)

Array converted to bytes:
b'\n\x00\x00\x00\x14\x00\x00\x00\x1e\x00\x00\x00(\x00\x00\x002\x00\x00\x00'

Array restored from bytes:
[10 20 30 40 50]


Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.

In [72]:

original_list = [1, 2, 3, 4, 5]
# Convert list to NumPy array
array = np.array(original_list)

# Convert array back to list
final_list = array.tolist()

# Check if both lists are equal
are_equal = original_list == final_list


print("Original list:", original_list)
print("Final list after conversions:", final_list)
print("Are both lists equal?", are_equal)

Original list: [1, 2, 3, 4, 5]
Final list after conversions: [1, 2, 3, 4, 5]
Are both lists equal? True
